"""
User Model - Example database model

Generated by REROUTE
"""
{% if cookiecutter.database_type == 'mongodb' %}from pydantic import BaseModel, Field
from bson import ObjectId
from typing import Optional
from datetime import datetime, timezone


class UserModel(BaseModel):
    id: Optional[str] = Field(default=None, alias="_id")
    username: str
    email: str
    is_active: bool = True
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Config:
        populate_by_name = True
        json_encoders = {ObjectId: str}
{% else %}from sqlalchemy import Column, Integer, String, Boolean, DateTime
from datetime import datetime, timezone
from app.database import Base


class User(Base):
    """User model with common authentication fields"""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, nullable=False, index=True)
    email = Column(String(100), unique=True, nullable=False, index=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f"<User(id={self.id}, username='{self.username}')>"
{% endif %}
