"""
{{ cookiecutter.project_name }} - FastAPI Application

Generated by REROUTE
"""

from pathlib import Path
from fastapi import FastAPI
from reroute.adapters import FastAPIAdapter
from config import AppConfig

# Load environment variables (secure explicit loading)
AppConfig.load_from_env()


# Create FastAPI app
app = FastAPI(
    title="{{ cookiecutter.project_name }}",
    description="{{ cookiecutter.description }}",
    version="0.1.0"
)

# Initialize REROUTE adapter
adapter = FastAPIAdapter(
    fastapi_app=app,
    app_dir=Path(__file__).parent / "app",
    config=AppConfig
)

# Register all REROUTE routes
adapter.register_routes()


if __name__ == "__main__":
    # Run the REROUTE server
    adapter.run_server()
