"""
Database Configuration for {{ cookiecutter.project_name }}

Generated by REROUTE
"""
{% if cookiecutter.include_database %}{% if cookiecutter.database_type == 'mongodb' %}# MongoDB Configuration
from motor.motor_asyncio import AsyncIOMotorClient
import os

DATABASE_URL = os.getenv("REROUTE_DATABASE_URL", "mongodb://localhost:27017/{{ cookiecutter.project_name }}")

client = AsyncIOMotorClient(DATABASE_URL)
db = client.get_default_database()
{% else %}# SQLAlchemy Configuration
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base
from contextlib import contextmanager
import os

DATABASE_URL = os.getenv("REROUTE_DATABASE_URL", "{% if cookiecutter.database_type == 'postgresql' %}postgresql://YOUR_USER:YOUR_PASSWORD@localhost:5432/{{ cookiecutter.project_name }}{% elif cookiecutter.database_type == 'mysql' %}mysql+pymysql://YOUR_USER:YOUR_PASSWORD@localhost:3306/{{ cookiecutter.project_name }}{% elif cookiecutter.database_type == 'sqlite' %}sqlite:///./{{ cookiecutter.project_name }}.db{% endif %}")

engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
    pool_size=5,
    max_overflow=10
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


@contextmanager
def get_db():
    """Database session context manager"""
    db = SessionLocal()
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()


def init_db():
    """Create all tables"""
    Base.metadata.create_all(bind=engine)
{% endif %}{% else %}# No Database Configured
# This project was created without database support.
# To add database later, re-run with --database option or manually configure.

def init_db():
    """Placeholder - no database configured"""
    pass
{% endif %}
