"""
Root and Health Routes for {{ cookiecutter.project_name }}

Generated by REROUTE
"""

from fastapi import APIRouter
from config import AppConfig

# Create router for root endpoints
router = APIRouter(prefix="/api", tags=["root"])

@router.get("/")
def get():
    """Root endpoint"""
    return {
        "message": "Welcome to {{ cookiecutter.project_name }}",
        "docs": AppConfig.OpenAPI.DOCS_PATH,
        "framework": "REROUTE + FastAPI"
    }

@router.get("/health")
def health():
    """Health check endpoint"""
    return {"status": "healthy"}
