"""
Test cases for {{ cookiecutter.project_name }}

Generated by REROUTE
"""

import pytest
from fastapi.testclient import TestClient
from main import app


# Create test client
client = TestClient(app)


def test_root_endpoint():
    """Test the root endpoint"""
    response = client.get("/")
    assert response.status_code == 200
    data = response.json()
    assert "message" in data
    assert data["framework"] == "REROUTE + FastAPI"


def test_health_endpoint():
    """Test the health check endpoint"""
    response = client.get("/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "healthy"


def test_hello_get():
    """Test GET /hello endpoint"""
    response = client.get("/hello")
    assert response.status_code == 200
    data = response.json()
    assert "message" in data


def test_hello_post():
    """Test POST /hello endpoint"""
    response = client.post("/hello", json={"test": "data"})
    assert response.status_code == 200
    data = response.json()
    assert "message" in data


def test_hello_put():
    """Test PUT /hello endpoint"""
    response = client.put("/hello", json={"test": "data"})
    assert response.status_code == 200
    data = response.json()
    assert "message" in data


def test_hello_delete():
    """Test DELETE /hello endpoint"""
    response = client.delete("/hello")
    assert response.status_code == 200
    data = response.json()
    assert "message" in data


def test_404_not_found():
    """Test that invalid routes return 404"""
    response = client.get("/nonexistent")
    assert response.status_code == 404
